# Generated by Django 2.2.5 on 2019-10-02 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191002_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(default='USA', max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField(choices=[(0, 'Purchase'), (1, 'Borrow')], default=1)),
                ('order_Date', models.DateField(default=django.utils.timezone.now)),
                ('books', models.ManyToManyField(blank=True, to='myapp.Book')),
            ],
        ),
    ]
