# Generated by Django 2.2.5 on 2019-10-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191002_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
